### ISSUE TITLE
Vault not found

### ISSUE THREAD

**Issue by dgk4201** [ewestern/obsidian-clipper#3]
How do I configure the vault location. I gave it the URL for my vault.

**Comment by Programazing** [comment]
Assuming you're on Firefox, because I didn't see this add-on in the Chrome store, right-click the icon and go to **Manage Extension**, click the **Options** tab, then enter your vault name.

**Comment by IkelAtomig** [comment]
That should help.

**Comment by ewestern** [comment]
Yes, sorry I haven't followed this repo closely for a while 
@Programazing is correct.
